//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verdezul.IDH.Entidades.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"C:\\Documents and Settings\\Logic\\My Doc" +
            "uments\\Danny\\Crespo\\Verdezul.Fredos.Caja\\Caja.Datos\\Caja.Datos.mdf\";Integrated S" +
            "ecurity=True;User Instance=True")]
        public string Caja_DatosConnectionString {
            get {
                return ((string)(this["Caja_DatosConnectionString"]));
            }
            set {
                this["Caja_DatosConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=C:\\WINDOWS\\IDH\\IDH.Datos\\IDH.Datos.mdf;" +
            "Integrated Security=True;User Instance=True")]
        public string IDH_DatosConnectionString {
            get {
                return ((string)(this["IDH_DatosConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"E:\\My Developments\\IDH\\IDH.Datos\\IDH.D" +
            "atos.mdf\";Integrated Security=True;User Instance=True")]
        public string IDH_DatosConnectionString1 {
            get {
                return ((string)(this["IDH_DatosConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=C:\\WINDOWS\\IDH\\Verdezul.IDH.Presentacio" +
            "n\\Datos\\IDH.Datos.mdf;Integrated Security=True;User Instance=True")]
        public string IDH_DatosConnectionString2 {
            get {
                return ((string)(this["IDH_DatosConnectionString2"]));
            }
        }
    }
}
